# Generated by Django 4.2.3 on 2023-08-16 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='iamge',
            new_name='image',
        ),
    ]
